// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://inoardprdannvhhequph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlub2FyZHByZGFubnZoaGVxdXBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMDg1ODksImV4cCI6MjA2MDg4NDU4OX0.utHebZgJluH1I43c8foPMxiazFdMWz-UEkxzxsnKkwc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);